# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "INFO"
  url = "info"
  weight = 10

[[main]]
  name = "SCHEDULE"
  url = "schedule"
  weight = 15

[[main]]
  name = "PREWORK"
  url = "prework"
  weight = 20

# [[main]]
#   name = "MATERIALS"
#   url = "materials"
#   weight = 30

[[main]]
  name = "PEOPLE"
  url = "people"
  weight = 40

[[main]]
  pre = "<i class=\"fab fa-github fa-lg\"></i>"
  name = ""
  url = "https://github.com/wjakethompson/tidyds-2021"
  weight = 50
